const globalTokens = {
  // Color
  inherit: "inherit",
  transparent: "transparent",

  hal_white: "#ffffff",
  hal_grey_l_95: "#f2f2f2",
  hal_grey_l_90: "#e6e6e6",
  hal_grey_l_80: "#cccccc",
  hal_grey_l_75: "#bfbfbf",
  hal_grey_l_60: "#999999",
  hal_grey_s_40: "#666666",
  hal_black: "#000000",
  darkWhite: "#eeeeee",
  lightGrey: "#D9D9D9",
  softGrey: "#cecece",
  lighterGrey: "#F8F8F8",
  lighterBlack: "#b1b1b1",
  mediumBlack: "#676767",
  mediumGreyBlack: "#dbdbdb",
  softBlack: "#565656",

  hal_purple_l_95: "#f2eafa",
  hal_purple_l_90: "#e5d5f6",
  hal_purple_l_65: "#a46ede",
  hal_purple_s_38: "#5f249f",
  hal_purple_d_30: "#4b1c7d",
  hal_purple_d_20: "#321353",
  purple: "#6f2c91",
  mediumPurple: "#ead8f3",
  lightPurple: "#f5ebf9",
  lighterPurple: "#d0bddb",
  violet: "#8800F6",

  hal_blue_l_95: "#e6f4ff",
  hal_blue_l_80: "#99d5ff",
  hal_blue_l_50: "#0095ff",
  hal_blue_l_45: "#0086e6",
  hal_blue_s_35: "#0067b3",
  hal_blue_d_20: "#003c66",
  blue: "#005FCC",
  darkBlue: "#006BF6",
  softBlue: "#b1cee6",
  mediumWhite: "#f9f9f9",
  lightBlue: "#CEE0F5",

  hal_red_l_95: "#ffe6e9",
  hal_red_l_80: "#fe9aa7",
  hal_red_l_60: "#fe344f",
  hal_red_s_41: "#d0011b",
  hal_red_d_30: "#980115",
  hal_red_d_20: "#65010e",

  hal_green_l_95: "#eafaef",
  hal_green_l_80: "#acecbe",
  hal_green_s_39: "#24a148",
  hal_green_d_30: "#1c7d38",
  hal_green_d_20: "#135325",
  lightGreen: "#DBF1C4",

  hal_yellow_l_95: "#fef9e6",
  hal_yellow_l_80: "#fbe89d",
  hal_yellow_s_57: "#f7cf2b",
  hal_yellow_d_40: "#c59f07",
  hal_yellow_d_30: "#947705",
  lightYellow: "#FCF2BD",

  hal_orange_s_54: "#f38f20",

  lightPink: "#F9CFCF",

  // Typography
  type_sans: "Open Sans, sans-serif",

  type_scale_root: "16px",
  type_scale_08: "3.75rem",
  type_scale_07: "3rem",
  type_scale_06: "2rem",
  type_scale_05: "1.5rem",
  type_scale_04: "1.25rem",
  type_scale_03: "1rem",
  type_scale_02: "0.875rem",
  type_scale_01: "0.75rem",

  type_light: "300",
  type_regular: "400",
  type_semibold: "600",

  type_bold: "bold",
  type_italic: "italic",
  type_normal: "normal",

  type_spacing_tight_02: "-0.05em",
  type_spacing_tight_01: "-0.025em",
  type_spacing_normal: "0",
  type_spacing_wide_01: "0.025em",
  type_spacing_wide_02: "0.05em",
  type_spacing_wide_03: "0.1em",

  type_initial: "initial",
  type_uppercase: "uppercase",
  type_no_line: "none",
  type_underline: "underline",
  type_line_through: "line-through",

  type_leading_compact_03: "1em",
  type_leading_compact_02: "1.25em",
  type_leading_compact_01: "1.365em",
  type_leading_normal: "1.5em",
  type_leading_loose_01: "1.75em",
  type_leading_loose_02: "2em",

  // Spacing
  spacing_00: "0rem",
  spacing_01: "0.125rem",
  spacing_02: "0.25rem",
  spacing_03: "0.5rem",
  spacing_04: "0.75rem",
  spacing_05: "1rem",
  spacing_06: "1.5rem",
  spacing_07: "2rem",
  spacing_08: "2.5rem",
  spacing_09: "3rem",
  spacing_10: "3.5rem",
  spacing_11: "4rem",
  spacing_12: "5rem",
  spacing_13: "6rem",
  spacing_14: "7rem",

  // Border
  border_width_01: "1px",
  border_width_02: "2px",

  border_radius_01: "2px",
  border_radius_02: "4px",

  border_solid: "solid",
  border_none: "none",  
};

export const componentTokens = {
  "--fontFamily": globalTokens.type_sans,
  //ACCORDION
  "--accordion-backgroundColor": globalTokens.hal_black,
  "--accordion-arrowColor": globalTokens.purple,
  "--accordion-hoverBackgroundColor": globalTokens.lightPurple,
  //Font
  "--accordion-fontColorBase": globalTokens.hal_grey_s_40,
  "--accordion-disabledFontColor": globalTokens.hal_grey_l_75,
  //Title
  "--accordion-titleFontFamily": globalTokens.type_sans,
  "--accordion-titleFontSize": globalTokens.type_scale_03,
  "--accordion-titleFontWeight": globalTokens.type_regular,
  "--accordion-titleFontStyle": globalTokens.type_normal,
  "--accordion-titleFontColor": "",
  "--accordion-titleMarginRight": "48px",
  "--accordion-titleMarginLeft": "0px",
  "--accordion-titleMarginTop": "0px",
  "--accordion-titleMarginBottom": "0px",
  //AssistiveText
  "--accordion-assistiveTextFontFamily": globalTokens.type_sans,
  "--accordion-assistiveTextFontSize": globalTokens.type_scale_03,
  "--accordion-assistiveTextFontWeight": globalTokens.type_light,
  "--accordion-assistiveTextFontStyle": globalTokens.type_italic,
  "--accordion-assistiveTextFontColor": "",
  "--accordion-assistiveTextLetterSpacing": globalTokens.type_spacing_wide_01,
  "--accordion-assistiveTextMinWidth": "100px",
  "--accordion-assistiveTextMarginRight": "0px",
  "--accordion-assistiveTextMarginLeft": "0px",
  "--accordion-assistiveTextMarginTop": "1px",
  "--accordion-assistiveTextMarginBottom": "0px",
  //CustomContent
  "--accordion-customContentFontFamily": globalTokens.type_sans,
  "--accordion-customContentFontSize": globalTokens.type_scale_03,
  "--accordion-customContentFontWeight": globalTokens.type_light,
  "--accordion-customContentFontColor": "",
  //Header
  "--accordion-headerPaddingLeft": "16px",
  "--accordion-headerPaddingRight": "16px",
  "--accordion-headerPaddingTop": "0px",
  "--accordion-headerPaddingBottom": "0px",
  "--accordion-headerFocusBorderStyle": "auto",
  "--accordion-headerFocusBorderThickness": "1px",
  "--accordion-headerFocusBorderColor": globalTokens.purple,
  //Size
  "--accordion-minHeight": "48px",
  "--accordion-minWidth": "280px",
  //Icon
  "--accordion-iconMaxHeight": "24px",
  "--accordion-iconMaxWidth": "24px",
  "--accordion-iconMarginLeft": "0px",
  "--accordion-iconMarginRigth": "12px",
  //Border/BoxShadow
  "--accordion-borderRadius": "4px",
  "--accordion-boxShadowOffsetX": "0px",
  "--accordion-boxShadowOffsetY": "6px",
  "--accordion-boxShadowBlur": "10px",
  "--accordion-boxShadowColor": "#00000024",
  //Separator
  "--accordion-accordionGroupSeparatorBorderColor": "#00000024",
  "--accordion-accordionGroupSeparatorBorderThickness": "1px",
  "--accordion-accordionGroupSeparatorBorderRadius": "0px",
  "--accordion-accordionGroupSeparatorBorderStyle": "solid",

  //ALERT
  "--alert-infoColor": globalTokens.lightBlue,
  "--alert-successColor": globalTokens.lightGreen,
  "--alert-warningColor": globalTokens.lightYellow,
  "--alert-errorColor": globalTokens.lightPink,
  "--alert-overlayColor": globalTokens.hal_black,
  "--alert-overlayOpacity": "0.8",
  "--alert-focusColor": globalTokens.blue, //ponerlo en el componente
  // Title
  "--alert-height": "48px",
  "--alert-titleFontFamily": globalTokens.type_sans,
  "--alert-titleFontSize": globalTokens.type_scale_01,
  "--alert-titleFontColor": globalTokens.hal_black,
  "--alert-titleFontWeight": globalTokens.type_bold,
  "--alert-titleFontStyle": globalTokens.type_normal,
  "--alert-titleTextTransform": globalTokens.type_uppercase,
  "--alert-titlePaddingRight": "10px",
  "--alert-titlePaddingLeft": "12px",
  "--alert-titlePaddingTop": "0px",
  "--alert-titlePaddingBottom": "0px",
  //Content
  "--alert-contentFontFamily": globalTokens.type_sans,
  "--alert-contentFontSize": globalTokens.type_scale_01,
  "--alert-contentFontColor": globalTokens.hal_black,
  "--alert-contentFontWeight": globalTokens.type_normal,
  "--alert-contentPaddingLeft": "46px",
  "--alert-contentPaddingRight": "12px",
  "--alert-contentPaddingTop": "8px",
  "--alert-contentPaddingBottom": "20px",
  //InlineText
  "--alert-inlineTextPaddingLeft": "10px",
  "--alert-inlineTextPaddingRight": "22px",
  "--alert-inlineTextPaddingTop": "0px",
  "--alert-inlineTextPaddingBottom": "0px",
  //Icon
  "--alert-iconPaddingLeft": "12px",
  "--alert-iconPaddingRight": "0px",
  "--alert-iconPaddingTop": "0px",
  "--alert-iconPaddingBottom": "0px",
  "--alert-iconSize": "20px",
  //Box/Border
  "--alert-boxShadowOffsetX": "0px",
  "--alert-boxShadowOffsetY": "3px",
  "--alert-boxShadowBlur": "6px",
  "--alert-boxShadowColor": "#00000012",
  "--alert-borderRadius": "4px",
  "--alert-borderStyle": globalTokens.type_no_line,
  "--alert-borderThickness": "0px",
  "--alert-borderColor": globalTokens.transparent,

  //BOX
  "--box-backgroundColor": globalTokens.hal_white,

  "--box-fontFamily": globalTokens.type_sans,
  "--box-fontSize": globalTokens.type_scale_02,
  "--box-fontWeight": globalTokens.type_normal,
  "--box-fontColor": globalTokens.hal_black,
  "--box-letterSpacing": globalTokens.type_spacing_wide_01,

  "--box-borderRadius": "4px",
  "--box-borderThickness": "0px",
  "--box-borderColor": globalTokens.transparent,
  "--box-borderStyle": globalTokens.type_no_line,

  "--box-noneShadowDepthShadowOffsetX": "none",
  "--box-noneShadowDepthShadowOffsetY": "none",
  "--box-noneShadowDepthShadowBlur": "none",
  "--box-noneShadowDepthShadowSpread": "none",
  "--box-noneShadowDepthShadowColor": globalTokens.transparent,
  "--box-oneShadowDepthShadowOffsetX": "0px",
  "--box-oneShadowDepthShadowOffsetY": "2px",
  "--box-oneShadowDepthShadowBlur": "1px",
  "--box-oneShadowDepthShadowSpread": "-1px",
  "--box-oneShadowDepthShadowColor": "#00000033",
  "--box-twoShadowDepthShadowOffsetX": "0px",
  "--box-twoShadowDepthShadowOffsetY": "3px",
  "--box-twoShadowDepthShadowBlur": "3px",
  "--box-twoShadowDepthShadowSpread": "-2px",
  "--box-twoShadowDepthShadowColor": "#00000033",

  //BUTTON
  "--button-primaryBackgroundColor": globalTokens.purple,
  "--button-primaryBackgroundColorOnDark": "#581B81",
  "--button-primaryHoverBackgroundColor": globalTokens.hal_black,
  "--button-primaryHoverBackgroundColorOnDark": "#581B81",
  "--button-primaryFontColor": globalTokens.hal_white,
  "--button-primaryFontColorOnDark": globalTokens.hal_black,
  "--button-primaryHoverFontColor": globalTokens.hal_white,
  "--button-primaryHoverFontColorOnDark": globalTokens.hal_black,
  "--button-disabledPrimaryBackgroundColor": globalTokens.lighterPurple,
  "--button-primaryActiveBackgroundColor": globalTokens.mediumBlack,
  "--button-primaryActiveBackgroundColorOnDark": "#581B81",
  "--button-primaryDisabledBackgroundColor": globalTokens.lighterPurple,
  "--button-primaryDisabledBackgroundColorOnDark": "#ffffff57",
  "--button-primaryDisabledFontColor": globalTokens.hal_white,
  "--button-primaryDisabledFontColorOnDark": globalTokens.hal_black,
  "--button-primaryBorderColor": globalTokens.transparent,
  "--button-primaryBorderColorOnDark": globalTokens.transparent,
  "--button-primaryBorderThickness": "0px",
  "--button-primaryBorderStyle": "none",
  "--button-primaryBorderRadius": "4px",
  "--button-primaryFontFamily": globalTokens.type_sans,
  "--button-primaryFontSize": globalTokens.type_scale_03,
  "--button-primaryFontWeight": globalTokens.type_regular,
  "--button-primaryPaddingTop": "12px",
  "--button-primaryPaddingBottom": "12px",
  "--button-secondaryOutlinedColor": globalTokens.purple,
  "--button-secondaryOutlinedColorOnDark": "#6A229A",
  "--button-secondaryBackgroundColor": globalTokens.transparent,
  "--button-secondaryBackgroundColorOnDark": globalTokens.transparent,
  "--button-secondaryHoverOutlinedColor": globalTokens.hal_black,
  "--button-secondaryHoverOutlinedColorOnDark": "#6A229A",
  "--button-secondaryFontColor": globalTokens.hal_black,
  "--button-secondaryFontColorOnDark": globalTokens.hal_white,
  "--button-secondaryHoverFontColor": globalTokens.hal_black,
  "--button-secondaryHoverFontColorOnDark": globalTokens.hal_white,
  "--button-secondaryActiveBackgroundColor": globalTokens.mediumGreyBlack,
  "--button-secondaryActiveBackgroundColorOnDark": "#FFFFFF29",
  "--button-secondaryHoverBackgroundColor": globalTokens.darkWhite,
  "--button-secondaryHoverBackgroundColorOnDark": "#FFFFFF14",
  "--button-secondaryDisabledOutlinedColor": globalTokens.lighterPurple,
  "--button-secondaryDisabledOutlinedColorOnDark": "#575757",
  "--button-secondaryDisabledFontColor": globalTokens.lighterBlack,
  "--button-secondaryDisabledFontColorOnDark": "#575757",
  "--button-secondaryBorderThickness": "1px",
  "--button-secondaryBorderStyle": "solid",
  "--button-secondaryBorderRadius": "4px",
  "--button-secondaryFontFamily": globalTokens.type_sans,
  "--button-secondaryFontSize": globalTokens.type_scale_03,
  "--button-secondaryFontWeight": globalTokens.type_regular,
  "--button-secondaryPaddingTop": "10px",
  "--button-secondaryPaddingBottom": "10px",
  "--button-textBackgroundColor": globalTokens.transparent,
  "--button-textBackgroundColorOnDark": globalTokens.transparent,
  "--button-textHoverBackgroundColor": globalTokens.hal_black,
  "--button-textHoverBackgroundColorOnDark": "#6A229A80",
  "--button-textFontColor": globalTokens.purple,
  "--button-textFontColorOnDark": globalTokens.hal_white,
  "--button-textHoverFontColor": globalTokens.hal_white,
  "--button-textHoverFontColorOnDark": globalTokens.hal_white,
  "--button-textActiveBackgroundColor": globalTokens.mediumBlack,
  "--button-textActiveBackgroundColorOnDark": "#581B81",
  "--button-textDisabledFontColor": globalTokens.lighterPurple,
  "--button-textDisabledBackgroundColor": globalTokens.transparent,
  "--button-textDisabledBackgroundColorOnDark": globalTokens.transparent,
  "--button-textDisabledFontColorOnDark": "#FFFFFF80",
  "--button-textBorderThickness": "0px",
  "--button-textBorderColor": globalTokens.transparent,
  "--button-textBorderColorOnDark": globalTokens.transparent,
  "--button-textBorderStyle": "none",
  "--button-textBorderRadius": "4px",
  "--button-textFontFamily": globalTokens.type_sans,
  "--button-textFontSize": globalTokens.type_scale_03,
  "--button-textFontWeight": globalTokens.type_regular,
  "--button-textPaddingTop": "12px",
  "--button-textPaddingBottom": "12px",
  "--button-focusColor": globalTokens.blue,
  "--button-labelFontLineHeight": "1em",
  "--button-labelLetterSpacing": globalTokens.type_spacing_wide_01,
  "--button-height": "40px",
  "--button-iconSize": "20px",

  //CARD
  "--card-height": "220px",
  "--card-width": "400px",

  //CHECKBOX
  "--checkbox-borderColor": globalTokens.hal_blue_s_35,
  "--checkbox-borderHoverColor": "#7BB0D6",
  "--checkbox-borderColorOnDark": globalTokens.hal_white,
  "--checkbox-borderHoverColorOnDark": globalTokens.lighterBlack,

  "--checkbox-backgroundColorChecked": globalTokens.hal_blue_s_35,
  "--checkbox-backgroundHoverColorChecked": "#7BB0D6",
  "--checkbox-backgroundColorCheckedOnDark": globalTokens.hal_white,
  "--checkbox-backgroundHoverColorCheckedOnDark": globalTokens.lighterBlack,

  "--checkbox-checkColor": globalTokens.hal_white,
  "--checkbox-checkColorOnDark": globalTokens.hal_blue_s_35,

  "--checkbox-fontColor": "inherit",
  "--checkbox-fontColorOnDark": globalTokens.hal_white,
  "--checkbox-fontFamily": globalTokens.type_sans,
  "--checkbox-fontSize": globalTokens.type_scale_03,
  "--checkbox-fontWeight": globalTokens.type_regular,
  "--checkbox-checkLabelSpacing": "10px",

  "--checkbox-disabledBackgroundColorChecked": globalTokens.softBlue,
  "--checkbox-disabledBackgroundColorCheckedOnDark": globalTokens.hal_grey_l_75,
  "--checkbox-disabledBorderColor": globalTokens.softBlue,
  "--checkbox-disabledBorderColorOnDark": globalTokens.hal_grey_l_75,
  "--checkbox-disabledCheckColor": globalTokens.hal_white,
  "--checkbox-disabledCheckColorOnDark": globalTokens.hal_white,
  "--checkbox-disabledFontColor": globalTokens.lighterBlack,
  "--checkbox-disabledFontColorOnDark": "#575757",

  "--checkbox-focusColor": globalTokens.blue,

  //CHIP
  "--chip-backgroundColor": "#e6e6e6",
  "--chip-borderColor": "transparent",
  "--chip-fontColor": globalTokens.hal_black,
  "--chip-disabledBackgroundColor": globalTokens.hal_grey_l_95,
  "--chip-disabledFontColor": "#999999",
  "--chip-fontFamily": globalTokens.type_sans,
  "--chip-fontSize": globalTokens.type_scale_03,
  "--chip-fontWeight": "400",
  "--chip-fontStyle": "normal",
  "--chip-borderRadius": "50px",
  "--chip-borderThickness": "2px",
  "--chip-borderStyle": "solid",
  "--chip-height": "18px",
  "--chip-contentPaddingLeft": "16px",
  "--chip-contentPaddingRight": "16px",
  "--chip-contentPaddingTop": "10px",
  "--chip-contentPaddingBottom": "10px",
  "--chip-iconSize": "24px",
  "--chip-iconPaddingLeft": "0px",
  "--chip-iconPaddingRight": "0px",
  "--chip-iconColor": globalTokens.hal_black,
  "--chip-disabledIconColor": "#999999", 
  "--chip-focusColor": globalTokens.blue,

  //DATE
  "--date-pickerSelectedDateBackgroundColor": globalTokens.purple,
  "--date-pickerSelectedDateColor": globalTokens.hal_white,
  "--date-pickerBackgroundColor": globalTokens.hal_white,
  "--date-pickerActualDate": globalTokens.lightGrey,
  "--date-pickerFontColor": globalTokens.hal_black,
  "--date-pickerHoverDateFontColor": globalTokens.hal_black,
  "--date-pickerHoverDateBackgroundColor": globalTokens.lighterPurple,
  "--date-focusColor": globalTokens.blue,
  "--date-pickerHoverHeaderColor": "#0000001F",
  "--date-pickerYearColor": globalTokens.hal_black,
  "--date-pickerLabelColor": globalTokens.lighterBlack,
  "--date-pickerWeekLabelColor": globalTokens.lighterBlack,
  "--date-pickerBackgroundColorMonthArrows": globalTokens.transparent,
  "--date-fontFamily": globalTokens.type_sans,
  "--date-pickerHeight": "300px",
  "--date-pickerWidth": "290px",

  //DIALOG
  "--dialog-overlayColor": globalTokens.hal_black,
  "--dialog-overlayOpacity": "0.8",
  "--dialog-backgroundColor": globalTokens.hal_white,

  "--dialog-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--dialog-scrollBarTrackColor": globalTokens.lightGrey,

  "--dialog-fontFamily": globalTokens.type_sans,
  "--dialog-fontSize": globalTokens.type_scale_03,
  "--dialog-fontWeight": globalTokens.type_regular,
  "--dialog-fontColor": globalTokens.hal_black,

  "--dialog-closeIconWidth": "34px",
  "--dialog-closeIconHeight": "34px",
  "--dialog-closeIconTopPosition": "20px",
  "--dialog-closeIconRightPosition": "20px",
  "--dialog-closeIconBackgroundColor": "none",
  "--dialog-closeIconColor": globalTokens.hal_black,
  "--dialog-closeIconBorderColor": globalTokens.type_no_line,
  "--dialog-closeIconBorderThickness": "0px",
  "--dialog-closeIconBorderStyle": "solid",
  "--dialog-closeIconBorderRadius": "0px",

  "--dialog-boxShadowOffsetX": "0px",
  "--dialog-boxShadowOffsetY": "1px",
  "--dialog-boxShadowBlur": "3px",
  "--dialog-boxShadowColor": "rgba(0, 0, 0, 0.2)",

  //DROPDOWN
  "--dropdown-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--dropdown-scrollBarTrackColor": globalTokens.lightGrey,
  "--dropdown-focusColor": globalTokens.blue,
  "--dropdown-buttonBackgroundColor": globalTokens.hal_white,
  "--dropdown-buttonFontColor": globalTokens.hal_black,
  "--dropdown-buttonHoverBackgroundColor": globalTokens.hal_grey_l_95,
  "--dropdown-activeButtonBackgroundColor": globalTokens.lightGrey,
  "--dropdown-disabledButtonBackgroundColor": globalTokens.transparent,
  "--dropdown-disabledButtonFontColor": globalTokens.lighterBlack,
  "--dropdown-optionsListBackgroundColor": globalTokens.hal_white,
  "--dropdown-optionsListHoverBackgroundColor": globalTokens.hal_grey_l_95,
  "--dropdown-optionsListActiveBackgroundColor": globalTokens.lightGrey,
  "--dropdown-fontFamily": globalTokens.type_sans,
  "--dropdown-buttonFontSize": globalTokens.type_scale_03,
  "--dropdown-buttonFontStyle": globalTokens.type_normal,
  "--dropdown-buttonFontWeight": globalTokens.type_regular,
  "--dropdown-minHeight": "40px",
  "--dropdown-borderRadius": "2px",
  "--dropdown-borderStyle": "none",
  "--dropdown-borderThickness": "0px",
  "--dropdown-borderColor": globalTokens.transparent,
  "--dropdown-optionsHeight": "36px",
  "--dropdown-caretIconMarginRight": "0px",
  "--dropdown-caretIconMarginLeft": "0px",
  "--dropdown-caretIconMarginTop": "0px",
  "--dropdown-caretIconMarginBottom": "0px",
  "--dropdown-optionsFontColor": globalTokens.hal_black,
  "--dropdown-optionsFontSize": globalTokens.type_scale_03,
  "--dropdown-optionsFontStyle": globalTokens.type_normal,
  "--dropdown-optionsFontWeight": globalTokens.type_regular,
  "--dropdown-iconSize": "20px",
  "--dropdown-iconOptionSpacing": "12px",
  "--dropdown-iconColor": globalTokens.hal_black,

  //FOOTER
  "--footer-backgroundColor": globalTokens.hal_black,
  "--footer-fontColorBase": globalTokens.hal_white,
  "--footer-minHeight": "124px",

  "--footer-bottomLinksDividerColor": "#1489fb",
  "--footer-bottomLinksDividerThickness": "1px",
  "--footer-bottomLinksDividerStyle": "solid",
  "--footer-bottomLinksDividerSpacing": "6px",
  "--footer-bottomLinksFontFamily": "Open Sans, sans-serif",
  "--footer-bottomLinksFontSize": "0.75rem",
  "--footer-bottomLinksFontStyle": "normal",
  "--footer-bottomLinksFontWeight": "400",
  "--footer-bottomLinksFontColor": "",
  "--footer-bottomLinksTextDecoration": "none",

  "--footer-copyrightFontFamily": "Open Sans, sans-serif",
  "--footer-copyrightFontSize": "0.75rem",
  "--footer-copyrightFontStyle": "normal",
  "--footer-copyrightFontWeight": "400",
  "--footer-copyrightFontColor": "",

  "--footer-customContentFontFamily": "Open Sans, sans-serif",
  "--footer-customContentFontSize": "16px",
  "--footer-customContentFontStyle": "normal",
  "--footer-customContentFontWeight": "400",
  "--footer-customContentFontColor": "",

  "--footer-logo": "assets/dxc-logo-wh.svg",
  "--footer-logoHeight": "32px",
  "--footer-logoWidth": "auto",

  "--footer-socialIconSize": "24px",
  "--footer-socialIconsGutter": "16px",

  //HEADER
  "--header-backgroundColor": globalTokens.hal_white,
  "--header-customContentFontFamily": "",
  "--header-customContentFontStyle": globalTokens.type_normal,
  "--header-customContentFontColor": "",
  "--header-customContentFontSize": "",
  "--header-customContentFontWeight": globalTokens.type_regular,
  "--header-dropdownBackgroundColor": globalTokens.transparent,
  "--header-dropdownHoverBackgroundColor": globalTokens.transparent,
  "--header-fontColorBase": globalTokens.hal_black,
  "--header-fontFamilyBase": globalTokens.type_sans,
  "--header-fontSizeBase": globalTokens.type_scale_root,
  "--header-hamburguerFocusColor": globalTokens.blue,
  "--header-hamburguerFontFamily": "",
  "--header-hamburguerFontStyle": globalTokens.type_normal,
  "--header-hamburguerFontColor": "",
  "--header-hamburguerFontSize": "10px",
  "--header-hamburguerFontWeight": globalTokens.type_semibold,
  "--header-hamburguerColor": globalTokens.hal_black,
  "--header-hamburguerHoverColor": globalTokens.mediumGreyBlack,
  "--header-hamburguerTextTransform": globalTokens.type_uppercase,
  "--header-logoHeight": "32px",
  "--header-logoWidth": "auto",
  "--header-menuBackgroundColor": globalTokens.hal_white,
  "--header-menuZindex": "2000",
  "--header-menuTabletWidth": "60vw",
  "--header-menuMobileWidth": "100vw",
  "--header-menuCustomContentFontFamily": "",
  "--header-menuCustomContentFontStyle": globalTokens.type_normal,
  "--header-menuCustomContentFontColor": "",
  "--header-menuCustomContentFontSize": "",
  "--header-menuCustomContentFontWeight": globalTokens.type_regular,
  "--header-minHeight": "64px",
  "--header-overlayColor": globalTokens.softBlack,
  "--header-overlayOpacity": "0.7",
  "--header-overlayZindex": "1600",
  "--header-paddingTop": "0px",
  "--header-paddingBottom": "0px",
  "--header-paddingRight": "0px",
  "--header-paddingLeft": "20px",
  "--header-underlinedColor": globalTokens.hal_black,
  "--header-underlinedThickness": "2px",
  "--header-underlinedStyle": "solid",

  //HEADING
  "--heading-fontColorBase": globalTokens.inherit,
  "--heading-fontFamilyBase": globalTokens.type_sans,
  "--heading-level1FontColor": "",
  "--heading-level1FontFamily": "",
  "--heading-level1FontSize": globalTokens.type_scale_08,
  "--heading-level1FontStyle": globalTokens.type_normal,
  "--heading-level1FontWeight": globalTokens.type_regular,
  "--heading-level1LineHeight": globalTokens.type_leading_compact_01,
  "--heading-level1LetterSpacing": globalTokens.type_spacing_tight_01,
  "--heading-level2FontColor": "",
  "--heading-level2FontFamily": "",
  "--heading-level2FontSize": globalTokens.type_scale_07,
  "--heading-level2FontStyle": globalTokens.type_normal,
  "--heading-level2FontWeight": globalTokens.type_regular,
  "--heading-level2LineHeight": globalTokens.type_leading_normal,
  "--heading-level2LetterSpacing": globalTokens.type_spacing_normal,
  "--heading-level3FontColor": "",
  "--heading-level3FontFamily": "",
  "--heading-level3FontSize": globalTokens.type_scale_06,
  "--heading-level3FontStyle": globalTokens.type_normal,
  "--heading-level3FontWeight": globalTokens.type_regular,
  "--heading-level3LineHeight": globalTokens.type_leading_compact_01,
  "--heading-level3LetterSpacing": globalTokens.type_spacing_wide_01,
  "--heading-level4FontColor": "",
  "--heading-level4FontFamily": "",
  "--heading-level4FontSize": globalTokens.type_scale_05,
  "--heading-level4FontStyle": globalTokens.type_normal,
  "--heading-level4FontWeight": globalTokens.type_regular,
  "--heading-level4LineHeight": globalTokens.type_scale_05,
  "--heading-level4LetterSpacing": globalTokens.type_spacing_normal,
  "--heading-level5FontColor": "",
  "--heading-level5FontFamily": "",
  "--heading-level5FontSize": globalTokens.type_scale_04,
  "--heading-level5FontStyle": globalTokens.type_normal,
  "--heading-level5FontWeight": globalTokens.type_regular,
  "--heading-level5LineHeight": globalTokens.type_leading_normal,
  "--heading-level5LetterSpacing": globalTokens.type_spacing_wide_01,

  //INPUT TEXT
  "--inputText-optionHoverBackgroundColor": globalTokens.lightGrey,
  "--inputText-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--inputText-scrollBarTrackColor": globalTokens.lightGrey,
  "--inputText-assistiveTextFontColor": globalTokens.hal_black,
  "--inputText-assistiveTextFontColorOnDark": globalTokens.hal_white,
  "--inputText-assistiveTextFontSize": globalTokens.type_scale_01,
  "--inputText-assistiveTextFontStyle": globalTokens.type_normal,
  "--inputText-assistiveTextFontWeight": globalTokens.type_regular,
  "--inputText-disabledFontColor": globalTokens.lighterBlack,
  "--inputText-disabledFontColorOnDark": "#575757",
  "--inputText-errorColor": globalTokens.hal_red_s_41,
  "--inputText-errorColorOnDark": globalTokens.hal_red_l_60,
  "--inputText-fontColorBase": globalTokens.hal_black,
  "--inputText-fontColorBaseOnDark": globalTokens.hal_white,
  "--inputText-fontFamilyBase": globalTokens.type_sans,
  "--inputText-fontSizeBase": globalTokens.type_scale_root,
  "--inputText-hoverOptionColor": globalTokens.hal_black,
  "--inputText-labelFontSize": globalTokens.type_scale_03,
  "--inputText-prefixIconColor": globalTokens.hal_black,
  "--inputText-prefixIconColorOnDark": globalTokens.hal_white,
  "--inputText-prefixLabelFontColor": globalTokens.hal_black,
  "--inputText-prefixLabelFontColorOnDark": globalTokens.hal_white,
  "--inputText-prefixLabelFontSize": globalTokens.type_scale_03,
  "--inputText-prefixLabelFontStyle": globalTokens.type_normal,
  "--inputText-prefixLabelFontWeight": globalTokens.type_regular,
  "--inputText-suffixIconColor": globalTokens.hal_black,
  "--inputText-suffixIconColorOnDark": globalTokens.hal_white,
  "--inputText-suffixLabelFontColor": globalTokens.hal_black,
  "--inputText-suffixLabelFontColorOnDark": globalTokens.hal_white,
  "--inputText-suffixLabelFontSize": globalTokens.type_scale_03,
  "--inputText-suffixLabelFontStyle": globalTokens.type_normal,
  "--inputText-suffixLabelFontWeight": globalTokens.type_regular,
  "--inputText-underlineColor": globalTokens.hal_black,
  "--inputText-underlineColorOnDark": globalTokens.hal_white,
  "--inputText-underlineFocusColor": globalTokens.hal_black,
  "--inputText-underlineFocusColorOnDark": globalTokens.hal_white,
  "--inputText-underlineThickness": "1px",
  "--inputText-optionActiveBackgroundColor": "#D9D9D9",
  "--inputText-optionFocusColor": "#005FCC",

  //LINK
  "--link-fontColor": globalTokens.blue,
  "--link-visitedFontColor": globalTokens.violet,
  "--link-disabledColor": globalTokens.lightGrey,
  "--link-hoverFontColor": globalTokens.darkBlue,
  "--link-underlinedBackgroundColor": globalTokens.blue,
  "--link-fontFamily": globalTokens.inherit,
  "--link-fontSize": "16px",
  "--link-fontStyle": globalTokens.type_normal,
  "--link-fontWeight": globalTokens.type_regular,
  "--link-iconSize": "16px",
  "--link-iconGutter": "4px",
  "--link-underlineSpacing": "1px",
  "--link-underlineStyle": "solid",
  "--link-underlineThickness": "1px",
  "--link-hoverUnderlineColor": globalTokens.hal_blue_s_35,
  "--link-visitedUnderlineColor": globalTokens.purple,
  "--link-activeFontColor": globalTokens.hal_black,
  "--link-activeUnderlineColor": globalTokens.hal_black,
  "--link-focusColor": globalTokens.hal_blue_s_35,

  //PAGINATOR
  "--paginator-backgroundColor": globalTokens.darkWhite,
  "--paginator-fontColor": globalTokens.hal_black,
  "--paginator-fontFamily": globalTokens.type_sans,
  "--paginator-fontSize": globalTokens.type_scale_02,
  "--paginator-fontStyle": globalTokens.type_normal,
  "--paginator-fontWeight": globalTokens.type_regular,
  "--paginator-height": "64px",
  "--paginator-width": "100%",
  "--paginator-marginRight": "40px",
  "--paginator-marginLeft": "20px",
  "--paginator-itemsPerPageSelectorMarginLeft": "0px",
  "--paginator-itemsPerPageSelectorMarginRight": "30px",
  "--paginator-pageSelectorMarginRight": "30px",
  "--paginator-pageSelectorMarginLeft": "0px",
  "--paginator-totalItemsContainerMarginRight": "30px",
  "--paginator-totalItemsContainerMarginLeft": "0px",

  //PROGRESSBAR
  "--progressBar-trackLineColor": globalTokens.purple,
  "--progressBar-totalLineColor": globalTokens.softGrey,
  "--progressBar-overlayColor": globalTokens.hal_black,
  "--progressBar-labelFontFamily": globalTokens.type_sans,
  "--progressBar-labelFontSize": globalTokens.type_scale_01,
  "--progressBar-labelFontStyle": globalTokens.type_normal,
  "--progressBar-labelFontWeight": globalTokens.type_regular,
  "--progressBar-labelFontColor": globalTokens.hal_black,
  "--progressBar-labelFontTextTransform": globalTokens.type_uppercase,
  "--progressBar-valueFontFamily": globalTokens.type_sans,
  "--progressBar-valueFontSize": globalTokens.type_scale_01,
  "--progressBar-valueFontStyle": globalTokens.type_normal,
  "--progressBar-valueFontWeight": globalTokens.type_regular,
  "--progressBar-valueFontColor": globalTokens.hal_black,
  "--progressBar-valueFontTextTransform": globalTokens.type_uppercase,
  "--progressBar-thickness": "9px",
  "--progressBar-borderRadius": "5px",
  "--progressBar-overlayOpacity": "0.8",

  //RADIO
  "--radio-color": globalTokens.hal_black,
  "--radio-disabledColor": globalTokens.lighterBlack,
  "--radio-fontColor": globalTokens.hal_black,
  "--radio-disabledFontColor": globalTokens.lighterBlack,
  "--radio-focusColor": globalTokens.blue,
  "--radio-circleLabelSpacing": "12px",
  "--radio-circleSize": "20px",
  "--radio-colorOnDark": globalTokens.hal_white,
  "--radio-disabledColorOnDark": "#575757",
  "--radio-disabledFontColorOnDark": "#575757",
  "--radio-focusColorOnDark": "#1682FF",
  "--radio-fontColorOnDark": globalTokens.hal_white,
  "--radio-fontFamily": globalTokens.type_sans,
  "--radio-fontSize": globalTokens.type_scale_root,
  "--radio-fontStyle": globalTokens.type_normal,
  "--radio-fontWeight": globalTokens.type_regular,

  //SELECT

  "--select-fontFamily": "Open Sans, sans-serif",

  "--select-labelFontSize": globalTokens.type_scale_03,
  "--select-labelFontStyle": "normal",
  "--select-labelFontWeight": "400",

  "--select-assistiveTextFontColor": globalTokens.hal_black,
  "--select-assistiveTextFontColorOnDark": globalTokens.hal_white,
  "--select-assistiveTextFontSize": globalTokens.type_scale_01,
  "--select-assistiveTextFontStyle": globalTokens.type_normal,
  "--select-assistiveTextFontWeight": globalTokens.type_regular,

  "--select-optionsBackgroundColor": globalTokens.hal_white,
  "--select-optionsBorderColor": globalTokens.type_no_line,
  "--select-optionsBorderThickness": "0px",
  "--select-optionsBorderStyle": "solid",
  "--select-optionsFontColor": "",
  "--select-optionsFontSize": globalTokens.type_scale_root,
  "--select-optionsFontStyle": globalTokens.type_normal,
  "--select-optionsFontWeight": globalTokens.type_regular,

  "--select-iconOptionSpacing": "12px",
  "--select-iconColor": "",
  "--select-iconSize": "20px",
  "--select-selectedOptionBackgroundColor": globalTokens.lightGrey,
  "--select-selectedOptionBackgroundColorOnDark": globalTokens.lightGrey,
  "--select-hoveredOptionBackgroundColor": globalTokens.hal_grey_l_95,
  "--select-hoveredOptionBackgroundColorOnDark": globalTokens.hal_grey_l_95,
  "--select-optionPaddingBottom": "6px",
  "--select-optionPaddingTop": "6px",
  "--select-optionPaddingLeft": "16px",
  "--select-optionPaddingRight": "16px",
  "--select-checkboxOptionSpacing": "12px",

  "--select-color": globalTokens.hal_black,
  "--select-colorOnDark": globalTokens.hal_white,
  "--select-errorColor": globalTokens.hal_red_s_41,
  "--select-errorColorOnDark": globalTokens.hal_red_l_60,

  "--select-required": globalTokens.hal_red_s_41,

  "--select-focusColor": globalTokens.blue,
  "--select-focusColorOnDark": globalTokens.blue,

  "--select-disabledColor": globalTokens.lighterBlack,
  "--select-disabledColorOnDark": "#575757",

  "--select-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--select-scrollBarTrackColor": globalTokens.lightGrey,

  //SIDENAV
  "--sidenav-backgroundColor": globalTokens.lighterGrey,
  "--sidenav-arrowContainerColor": globalTokens.lightGrey,
  "--sidenav-arrowColor": globalTokens.hal_black,
  "--sidenav-customContentFontFamily": globalTokens.type_sans,
  "--sidenav-customContentFontSize": "16px",
  "--sidenav-customContentFontStyle": globalTokens.type_normal,
  "--sidenav-customContentFontWeight": globalTokens.type_regular,
  "--sidenav-customContentFontColor": globalTokens.hal_black,
  "--sidenav-titleFontFamily": globalTokens.type_sans,
  "--sidenav-titleFontSize": globalTokens.type_scale_05,
  "--sidenav-titleFontStyle": globalTokens.type_normal,
  "--sidenav-titleFontWeight": globalTokens.type_regular,
  "--sidenav-titleFontColor": "#000000de",
  "--sidenav-titleFontTextTransform": globalTokens.type_no_line,
  "--sidenav-titleFontLetterSpacing": globalTokens.type_spacing_normal,
  "--sidenav-subtitleFontFamily": globalTokens.type_sans,
  "--sidenav-subtitleFontSize": globalTokens.type_scale_01,
  "--sidenav-subtitleFontStyle": globalTokens.type_normal,
  "--sidenav-subtitleFontWeight": globalTokens.type_regular,
  "--sidenav-subtitleFontColor": "#00000099",
  "--sidenav-subtitleFontTextTransform": globalTokens.type_uppercase,
  "--sidenav-subtitleFontLetterSpacing": globalTokens.type_spacing_wide_03,
  "--sidenav-linkFontFamily": globalTokens.type_sans,
  "--sidenav-linkFontSize": globalTokens.type_scale_02,
  "--sidenav-linkFontStyle": globalTokens.type_normal,
  "--sidenav-linkFontWeight": globalTokens.type_regular,
  "--sidenav-linkFontColor": "#00000099",
  "--sidenav-linkFontTextTransform": globalTokens.type_no_line,
  "--sidenav-linkFontLetterSpacing": globalTokens.type_spacing_wide_01,
  "--sidenav-linkTextDecoration": "none",
  "--sidenav-linkMarginTop": "6px",
  "--sidenav-linkMarginRight": "18px",
  "--sidenav-linkMarginBottom": "6px",
  "--sidenav-linkMarginLeft": "18px",
  "--sidenav-scrollBarThumbColor": "#66666626",
  "--sidenav-scrollBarTrackColor": globalTokens.transparent,

  //SLIDER
  "--slider-fontFamily": globalTokens.type_sans,
  "--slider-fontSize": globalTokens.type_scale_03,
  "--slider-fontStyle": globalTokens.type_normal,
  "--slider-fontWeight": globalTokens.type_regular,
  "--slider-fontColor": globalTokens.hal_black,
  "--slider-fontColorOnDark": globalTokens.hal_white,
  "--slider-fontLetterSpacing": globalTokens.type_spacing_normal,
  "--slider-thumbHeight": "12px",
  "--slider-thumbWidth": "12px",
  "--slider-thumbVerticalPosition": "-6px",
  "--slider-thumbBackgroundColor": globalTokens.hal_blue_s_35,
  "--slider-thumbBackgroundColorOnDark": globalTokens.hal_blue_l_50,
  "--slider-activeThumbBackgroundColor": globalTokens.hal_blue_d_20,
  "--slider-activeThumbBackgroundColorOnDark": globalTokens.hal_blue_s_35,
  "--slider-dotsSize": "4px",
  "--slider-dotsVerticalPosition": "-1px",
  "--slider-tickMarkBackgroundColor": globalTokens.hal_blue_s_35,
  "--slider-tickMarkBackgroundColorOnDark": globalTokens.hal_blue_l_50,
  "--slider-lineThickness": "2px",
  "--slider-lineVerticalPosition": "0px",
  "--slider-trackLineColor": globalTokens.hal_blue_s_35,
  "--slider-trackLineColorOnDark": globalTokens.hal_blue_l_50,
  "--slider-totalLineColor": globalTokens.hal_grey_l_90,
  "--slider-totalLineColorOnDark": globalTokens.hal_grey_l_75,
  "--slider-disabledThumbVerticalPosition": "-6px",
  "--slider-disabledThumbBackgroundColor": globalTokens.hal_grey_l_75,
  "--slider-disabledThumbBackgroundColorOnDark": globalTokens.hal_grey_l_60,
  "--slider-disabledDotsVerticalPosition": "-1px",
  "--slider-disabledTickMarkBackgroundColor": globalTokens.hal_grey_l_75,
  "--slider-disabledTickMarkBackgroundColorOnDark": globalTokens.hal_grey_l_60,
  "--slider-disabledTrackLineColor": globalTokens.hal_blue_l_95,
  "--slider-disabledTrackLineColorOnDark": globalTokens.hal_grey_l_60,
  "--slider-disabledTotalLineColor": globalTokens.hal_grey_l_95,
  "--slider-disabledTotalLineColorOnDark": globalTokens.hal_grey_s_40,
  "--slider-focusColor": globalTokens.hal_blue_s_35,
  "--slider-focusColorOnDark": globalTokens.hal_blue_l_50,

  //SPINNER
  "--spinner-trackCircleColor": globalTokens.hal_purple_s_38,
  "--spinner-totalCircleColor": globalTokens.hal_white,
  "--spinner-overlayBackgroundColor": globalTokens.hal_black,
  "--spinner-labelFontFamily": globalTokens.type_sans,
  "--spinner-labelFontSize": globalTokens.type_scale_02,
  "--spinner-labelFontStyle": globalTokens.type_normal,
  "--spinner-labelFontWeight": globalTokens.type_regular,
  "--spinner-labelFontColor": globalTokens.hal_black,
  "--spinner-labelFontTextTransform": "none",
  "--spinner-labelLetterSpacing": globalTokens.type_spacing_normal,
  "--spinner-labelTextAlign": "center",
  "--spinner-progressValueFontFamily": globalTokens.type_sans,
  "--spinner-progressValueFontSize": globalTokens.type_scale_02,
  "--spinner-progressValueFontStyle": globalTokens.type_normal,
  "--spinner-progressValueFontWeight": globalTokens.type_semibold,
  "--spinner-progressValueFontColor": globalTokens.hal_black,
  "--spinner-progressValueLetterSpacing": globalTokens.type_spacing_normal,
  "--spinner-progressValueTextAlign": "center",
  "--spinner-overlayOpacity": "0.8",
  "--spinner-overlayTrackCircleColor": globalTokens.hal_purple_l_65,
  "--spinner-overlayLabelFontFamily": globalTokens.type_sans,
  "--spinner-overlayLabelFontSize": globalTokens.type_scale_02,
  "--spinner-overlayLabelFontStyle": globalTokens.type_normal,
  "--spinner-overlayLabelFontWeight": globalTokens.type_regular,
  "--spinner-overlayLabelFontColor": globalTokens.hal_white,
  "--spinner-overlayLabelFontTextTransform": "none",
  "--spinner-overlayLabelLetterSpacing": globalTokens.type_spacing_normal,
  "--spinner-overlayLabelTextAlign": "center",
  "--spinner-overlayProgressValueFontFamily": globalTokens.type_sans,
  "--spinner-overlayProgressValueFontSize": globalTokens.type_scale_02,
  "--spinner-overlayProgressValueFontStyle": globalTokens.type_normal,
  "--spinner-overlayProgressValueFontWeight": globalTokens.type_semibold,
  "--spinner-overlayProgressValueFontColor": globalTokens.hal_white,
  "--spinner-overlayProgressValueLetterSpacing":
    globalTokens.type_spacing_normal,
  "--spinner-overlayProgressValueTextAlign": "center",

  //SWITCH
  "--switch-requiredColor": globalTokens.hal_red_s_41,
  "--switch-checkedTrackBackgroundColor": globalTokens.purple,
  "--switch-checkedTrackBackgroundColorOnDark": globalTokens.purple,
  "--switch-checkedThumbBackgroundColor": globalTokens.hal_white,
  "--switch-checkedThumbBackgroundColorOnDark": globalTokens.hal_white,
  "--switch-uncheckedThumbBackgroundColor": globalTokens.hal_white,
  "--switch-uncheckedThumbBackgroundColorOnDark": globalTokens.hal_white,
  "--switch-uncheckedTrackBackgroundColor": globalTokens.lightGrey,
  "--switch-uncheckedTrackBackgroundColorOnDark": globalTokens.lightGrey,
  "--switch-disabledCheckedTrackBackgroundColor": globalTokens.lighterPurple,
  "--switch-disabledCheckedTrackBackgroundColorOnDark": "#1c0b24",
  "--switch-disabledCheckedThumbBackgroundColor": globalTokens.hal_white,
  "--switch-disabledCheckedThumbBackgroundColorOnDark": globalTokens.hal_white,
  "--switch-disabledUncheckedTrackBackgroundColor": globalTokens.hal_grey_l_95,
  "--switch-disabledUncheckedTrackBackgroundColorOnDark": "#363636",
  "--switch-disabledUncheckedThumbBackgroundColor": globalTokens.hal_white,
  "--switch-disabledUncheckedThumbBackgroundColorOnDark":
    globalTokens.hal_white,
  "--switch-disabledLabelFontColor": globalTokens.lighterBlack,
  "--switch-disabledLabelFontColorOnDark": "#575757",
  "--switch-disabledLabelFontStyle": globalTokens.type_normal,
  "--switch-labelFontFamily": globalTokens.type_sans,
  "--switch-labelFontSize": "16px",
  "--switch-labelFontStyle": globalTokens.type_normal,
  "--switch-labelFontWeight": globalTokens.type_regular,
  "--switch-labelFontColor": globalTokens.hal_black,
  "--switch-labelFontColorOnDark": globalTokens.hal_white,
  "--switch-thumbFocusColor": globalTokens.blue,
  "--switch-thumbFocusColorOnDark": "#1489FB",
  "--switch-thumbHeight": "24px",
  "--switch-thumbWidth": "24px",
  "--switch-thumbShift": "-2px",
  "--switch-trackHeight": "12px",
  "--switch-trackWidth": "60px",
  "--switch-spaceBetweenLabelSwitch": "0px",

  //TABLE
  "--table-rowSeparatorThickness": "1px",
  "--table-rowSeparatorStyle": "solid",
  "--table-rowSeparatorColor": globalTokens.lightGrey,
  "--table-dataBackgroundColor": globalTokens.hal_white,
  "--table-dataFontFamily": globalTokens.type_sans,
  "--table-dataFontSize": globalTokens.type_scale_root,
  "--table-dataFontStyle": globalTokens.type_normal,
  "--table-dataFontWeight": globalTokens.type_regular,
  "--table-dataFontColor": globalTokens.hal_black,
  "--table-dataFontTextTransform": "none",
  "--table-dataPaddingTop": "14px",
  "--table-dataPaddingBottom": "12px",
  "--table-dataPaddingRight": "20px",
  "--table-dataPaddingLeft": "40px",
  "--table-dataTextAlign": "left",
  "--table-dataTextLineHeight": "normal",
  "--table-headerBackgroundColor": globalTokens.purple,
  "--table-headerBorderRadius": "4px",
  "--table-headerFontFamily": globalTokens.type_sans,
  "--table-headerFontSize": globalTokens.type_scale_02,
  "--table-headerFontStyle": globalTokens.type_normal,
  "--table-headerFontWeight": globalTokens.type_regular,
  "--table-headerFontColor": globalTokens.hal_white,
  "--table-headerFontTextTransform": "none",
  "--table-headerPaddingTop": "16px",
  "--table-headerPaddingBottom": "16px",
  "--table-headerPaddingRight": "20px",
  "--table-headerPaddingLeft": "40px",
  "--table-headerTextAlign": "left",
  "--table-headerTextLineHeight": "normal",
  "--table-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--table-scrollBarTrackColor": globalTokens.lightGrey,
  "--table-sortIconColor": globalTokens.hal_white,

  //TABS
  "--tabs-fontFamily": globalTokens.type_sans,
  "--tabs-fontSize": globalTokens.type_scale_03,
  "--tabs-fontStyle": globalTokens.type_normal,
  "--tabs-fontWeight": globalTokens.type_semibold,
  "--tabs-fontTextTransform": "none",
  "--tabs-selectedBackgroundColor": globalTokens.hal_white,
  "--tabs-selectedFontColor": globalTokens.purple,
  "--tabs-selectedIconColor": globalTokens.purple,
  "--tabs-selectedUnderlineColor": globalTokens.purple,
  "--tabs-selectedUnderlineThickness": "",
  "--tabs-unselectedBackgroundColor": globalTokens.hal_white,
  "--tabs-unselectedFontColor": globalTokens.hal_grey_s_40,
  "--tabs-unselectedIconColor": globalTokens.hal_grey_s_40,
  "--tabs-disabledFontColor": globalTokens.hal_grey_l_75,
  "--tabs-disabledIconColor": globalTokens.hal_grey_l_75,
  "--tabs-disabledFontStyle": globalTokens.type_normal,
  "--tabs-hoverBackgroundColor": globalTokens.lightPurple,
  "--tabs-pressedBackgroundColor": globalTokens.mediumPurple,
  "--tabs-pressedFontWeight": globalTokens.type_semibold,
  "--tabs-dividerColor": globalTokens.hal_grey_l_75,
  "--tabs-dividerThickness": "1px",
  "--tabs-focusOutline": globalTokens.purple,
  "--tabs-scrollButtonsWidth": "48px",
  "--tabs-badgeBackgroundColor": globalTokens.hal_red_s_41,
  "--tabs-badgeFontFamily": globalTokens.type_sans,
  "--tabs-badgeFontSize": "10px",
  "--tabs-badgeFontStyle": globalTokens.type_normal,
  "--tabs-badgeFontWeight": "500",
  "--tabs-badgeFontColor": globalTokens.hal_white,
  "--tabs-badgeLetterSpacing": globalTokens.type_spacing_wide_02,
  "--tabs-badgeWidth": "16px",
  "--tabs-badgeHeight": "16px",
  "--tabs-badgeRadius": "10px",
  "--tabs-badgeWidthWithNotificationNumber": "23px",
  "--tabs-badgeHeightWithNotificationNumber": "17px",
  "--tabs-badgeRadiusWithNotificationNumber": "10px",

  //TAG
  "--tag-iconColor": globalTokens.hal_white,
  "--tag-fontStyle": globalTokens.type_normal,
  "--tag-fontTextTransform": globalTokens.type_uppercase,
  "--tag-height": "43px",
  "--tag-iconSectionWidth": "48px",
  "--tag-iconHeight": "24px",
  "--tag-iconWidth": "24px",

  //TEXTAREA
  "--textarea-disabledFontColor": globalTokens.lighterBlack,
  "--textarea-disabledFontColorOnDark": "#575757",
  "--textarea-errorColor": globalTokens.hal_red_s_41,
  "--textarea-errorColorOnDark": globalTokens.hal_red_l_60,
  "--textarea-assistiveTextFontFamily": globalTokens.type_sans,
  "--textarea-assistiveTextFontSize": globalTokens.type_scale_01,
  "--textarea-assistiveTextFontStyle": globalTokens.type_normal,
  "--textarea-assistiveTextFontWeight": globalTokens.type_regular,
  "--textarea-assistiveTextFontColor": globalTokens.hal_black,
  "--textarea-assistiveTextFontColorOnDark": globalTokens.hal_white,
  "--textarea-assistiveTextLetterSpacing": globalTokens.type_spacing_normal,
  "--textarea-customContentFontFamily": globalTokens.type_sans,
  "--textarea-customContentFontSize": globalTokens.type_scale_03,
  "--textarea-customContentFontStyle": globalTokens.type_normal,
  "--textarea-customContentFontWeight": globalTokens.type_regular,
  "--textarea-customContentFontColor": globalTokens.hal_black,
  "--textarea-customContentFontColorOnDark": globalTokens.hal_white,
  "--textarea-customContentLetterSpacing": globalTokens.type_spacing_normal,
  "--textarea-customContentLineHeight": "1.1875em",
  "--textarea-labelFontFamily": globalTokens.type_sans,
  "--textarea-labelFontSize": globalTokens.type_scale_03,
  "--textarea-labelFontStyle": globalTokens.type_normal,
  "--textarea-labelFontWeight": globalTokens.type_regular,
  "--textarea-labelFontColor": globalTokens.hal_black,
  "--textarea-labelFontColorOnDark": globalTokens.hal_white,
  "--textarea-labelLetterSpacing": globalTokens.type_spacing_normal,
  "--textarea-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--textarea-scrollBarThumbColorOnDark": globalTokens.hal_white,
  "--textarea-scrollBarTrackColor": globalTokens.lightGrey,
  "--textarea-scrollBarTrackColorOnDark": globalTokens.hal_grey_l_60,

  //TOGGLE GROUP
  "--toggleGroup-unselectedBackgroundColor": globalTokens.lightGrey,
  "--toggleGroup-unselectedBackgroundHoverColor": globalTokens.darkWhite,
  "--toggleGroup-unselectedFontColor": globalTokens.hal_black,
  "--toggleGroup-unselectedHoverFontColor": globalTokens.hal_black,
  "--toggleGroup-selectedBackgroundColor": globalTokens.purple,
  "--toggleGroup-selectedBackgroundHoverColor": globalTokens.hal_black,
  "--toggleGroup-selectedFontColor": globalTokens.hal_white,
  "--toggleGroup-selectedHoverFontColor": globalTokens.hal_white,
  "--toggleGroup-disabledSelectedBackgroundColor": globalTokens.lighterPurple,
  "--toggleGroup-disabledSelectedFontColor": globalTokens.hal_white,
  "--toggleGroup-disabledUnselectedBackgroundColor": globalTokens.hal_grey_l_95,
  "--toggleGroup-disabledUnselectedFontColor": globalTokens.lighterBlack,
  "--toggleGroup-fontFamily": globalTokens.type_sans,
  "--toggleGroup-fontSize": globalTokens.type_scale_02,
  "--toggleGroup-fontStyle": globalTokens.type_normal,
  "--toggleGroup-fontWeight": globalTokens.type_regular,
  "--toggleGroup-fontTextTransform": globalTokens.type_uppercase,
  "--toggleGroup-fontLetterSpacing": globalTokens.type_spacing_wide_02,
  "--toggleGroup-focusColor": "#005FCC",
  "--toggleGroup-iconSize": "20px",
  "--toggleGroup-iconPaddingTop": "10px",
  "--toggleGroup-iconPaddingBottom": "10px",
  "--toggleGroup-iconPaddingRight": "12px",
  "--toggleGroup-iconPaddingLeft": "12px",
  "--toggleGroup-labelPaddingTop": "12px",
  "--toggleGroup-labelPaddingBottom": "12px",
  "--toggleGroup-labelPaddingLeft": "30px",
  "--toggleGroup-labelPaddingRight": "30px",

  //UPLOAD
  "--upload-shadowColor": globalTokens.hal_grey_l_95,
  "--upload-fileHoverColor": globalTokens.darkWhite,
  "--upload-scrollBarThumbColor": globalTokens.hal_grey_s_40,
  "--upload-scrollBarTrackColor": globalTokens.lightGrey,
  "--upload-errorColor": globalTokens.hal_red_s_41,
  "--upload-backgroundColor": globalTokens.hal_white,
  "--upload-fontFamily": globalTokens.type_sans,
  "--upload-draggingAreaBackgroundColor": globalTokens.hal_grey_l_95,
  "--upload-dragAndDropIconColor": globalTokens.hal_black,
  "--upload-dragAndDropIconHeight": "43.5px",
  "--upload-dragAndDropIconWidth": "43.5px",
  "--upload-dragAndDropTitleFontSize": globalTokens.type_scale_04,
  "--upload-dragAndDropTitleFontStyle": globalTokens.type_normal,
  "--upload-dragAndDropTitleFontWeight": globalTokens.type_bold,
  "--upload-dragAndDropTitleFontTextTransform": "none",
  "--upload-dragAndDropTitleFontColor": globalTokens.hal_black,
  "--upload-dragAndDropDescriptionFontSize": globalTokens.type_scale_03,
  "--upload-dragAndDropDescriptionFontStyle": globalTokens.type_italic,
  "--upload-dragAndDropDescriptionFontWeight": globalTokens.type_normal,
  "--upload-dragAndDropTextDescriptionFontTextTransform": "none",
  "--upload-dragAndDropTextDescriptionFontColor": globalTokens.hal_grey_s_40,
  "--upload-dragAndDropDraggingStateIconColor": globalTokens.hal_grey_s_40,
  "--upload-dragAndDropDraggingStateIconHeight": "74.5px",
  "--upload-dragAndDropDraggingStateIconWidth": "74.5px",
  "--upload-dragAndDropDraggingStateFontSize": globalTokens.type_scale_03,
  "--upload-dragAndDropDraggingStateFontStyle": globalTokens.type_italic,
  "--upload-dragAndDropDraggingStateFontWeight": globalTokens.type_normal,
  "--upload-dragAndDropTextDraggingStateFontTextTransform": "none",
  "--upload-dragAndDropTextDraggingStateFontColor": globalTokens.hal_grey_s_40,
  "--upload-dragAndDropAreaIconColor": globalTokens.hal_grey_s_40,
  "--upload-dragAndDropAreaIconHeight": "24px",
  "--upload-dragAndDropAreaIconWidth": "24px",
  "--upload-dragAndDropAreaTextFontSize": globalTokens.type_scale_01,
  "--upload-dragAndDropAreaTextFontStyle": globalTokens.type_italic,
  "--upload-dragAndDropAreaTextFontWeight": globalTokens.type_regular,
  "--upload-dragAndDropAreaTextFontTextTransform": "none",
  "--upload-dragAndDropAreaTextFontColor": globalTokens.hal_grey_s_40,
  "--upload-fileDeleteIconColor": globalTokens.hal_black,
  "--upload-fileDeleteIconHeight": "30px",
  "--upload-fileDeleteIconWidth": "30px",
  "--upload-fileUnderlineColor": globalTokens.lightGrey,
  "--upload-fileUnderlineThickness": "1px",
  "--upload-fileNameFontSize": globalTokens.type_scale_03,
  "--upload-fileNameFontStyle": globalTokens.type_normal,
  "--upload-fileNameFontWeight": globalTokens.type_regular,
  "--upload-fileNameFontTextTransform": "none",
  "--upload-fileNameFontColor": globalTokens.hal_black,
  "--upload-fileTypeFontSize": globalTokens.type_scale_01,
  "--upload-fileTypeFontStyle": globalTokens.type_normal,
  "--upload-fileTypeFontWeight": globalTokens.type_regular,
  "--upload-fileTypeFontTextTransform": globalTokens.type_uppercase,
  "--upload-fileTypeFontColor": globalTokens.hal_grey_s_40,
  "--upload-fileUploadedIconColor": globalTokens.lightGrey,
  "--upload-fileUploadedIconHeight": "24px",
  "--upload-fileUploadedIconWidth": "24px",
  "--upload-filesUploadedTitleFontSize": globalTokens.type_scale_04,
  "--upload-filesUploadedTitleFontStyle": globalTokens.type_normal,
  "--upload-filesUploadedTitleFontWeight": globalTokens.type_regular,
  "--upload-filesUploadedTitleFontTextTransform": "none",
  "--upload-filesUploadedTitleFontColor": globalTokens.hal_black,
  "--upload-filesUploadedSubtitleFontSize": globalTokens.type_scale_01,
  "--upload-filesUploadedSubtitleFontStyle": globalTokens.type_normal,
  "--upload-filesUploadedSubtitleFontWeight": globalTokens.type_regular,
  "--upload-filesUploadedSubtitleFontTextTransform": "none",
  "--upload-filesUploadedSubtitleFontColor": globalTokens.hal_grey_s_40,
  "--upload-filesUploadedNumberFontWeight": globalTokens.type_bold,

  //WIZARD
  "--wizard-focusColor": globalTokens.blue,
  "--wizard-disabledBackgroundColor": globalTokens.lightGrey,
  "--wizard-disabledFontColor": globalTokens.hal_grey_s_40,
  "--wizard-stepContainerFontSize": globalTokens.type_scale_03,
  "--wizard-stepContainerFontFamily": globalTokens.type_sans,
  "--wizard-stepContainerFontStyle": globalTokens.type_normal,
  "--wizard-stepContainerFontWeight": globalTokens.type_regular,
  "--wizard-stepContainerLetterSpacing": globalTokens.type_spacing_wide_02,
  "--wizard-stepContainerFontColor": globalTokens.hal_black,
  "--wizard-stepContainerSelectedFontColor": globalTokens.hal_white,
  "--wizard-stepContainerSelectedBackgroundColor": globalTokens.purple,
  "--wizard-stepContainerBackgroundColor": globalTokens.hal_white,
  "--wizard-stepContainerIconSize": "20px",
  "--wizard-labelFontSize": globalTokens.type_scale_03,
  "--wizard-labelFontFamily": globalTokens.type_sans,
  "--wizard-labelFontStyle": globalTokens.type_normal,
  "--wizard-labelFontWeight": globalTokens.type_regular,
  "--wizard-labelLetterSpacing": globalTokens.type_spacing_normal,
  "--wizard-labelFontTextTransform": "none",
  "--wizard-labelTextAlign": "left",
  "--wizard-labelFontColor": globalTokens.hal_grey_s_40,
  "--wizard-labelActiveFontColor": globalTokens.hal_black,
  "--wizard-descriptionFontSize": globalTokens.type_scale_01,
  "--wizard-descriptionFontFamily": globalTokens.type_sans,
  "--wizard-descriptionFontStyle": globalTokens.type_normal,
  "--wizard-descriptionFontWeight": globalTokens.type_regular,
  "--wizard-descriptionLetterSpacing": globalTokens.type_spacing_wide_01,
  "--wizard-descriptionFontTextTransform": "none",
  "--wizard-descriptionFontColor": globalTokens.hal_grey_s_40,
  "--wizard-descriptionActiveFontColor": globalTokens.hal_black,
  "--wizard-descriptionTextAlign": "left",
  "--wizard-circleBorderThickness": "2px",
  "--wizard-circleBorderStyle": "solid",
  "--wizard-circleBorderRadius": "45px",
  "--wizard-circleBorderColor": globalTokens.hal_black,
  "--wizard-circleSelectedWidth": "32px",
  "--wizard-circleSelectedHeight": "32px",
  "--wizard-circleSelectedBorderThickness": "2px",
  "--wizard-circleSelectedBorderStyle": "solid",
  "--wizard-circleSelectedBorderRadius": "45px",
  "--wizard-circleSelectedBorderColor": globalTokens.purple,
  "--wizard-circleDisabledWidth": "32px",
  "--wizard-circleDisabledHeight": "32px",
  "--wizard-circleDisabledBorderThickness": "2px",
  "--wizard-circleDisabledBorderStyle": "solid",
  "--wizard-circleDisabledBorderRadius": "45px",
  "--wizard-circleDisabledBorderColor": globalTokens.lightGrey,
  "--wizard-circleWidth": "32px",
  "--wizard-circleHeight": "32px",
  "--wizard-separatorBorderThickness": "1px",
  "--wizard-separatorBorderStyle": "solid",
  "--wizard-separatorColor": globalTokens.lightGrey,
};

export const componentIcons = {
  footer: {
    logo: "assets/dxc-logo-wh.svg",
  },
  header: {
    logo: "assets/DXC_Logo_Black_RGB.svg",
    logoResponsive: "assets/DXC_Logo_Black_RGB.svg",
  },
};
