export const darkTheme = {
  accordion: {
    accentColor: "#30da1b",
    textColor: "#666666",
  },
  button: {
    baseColor: "transparent",
    hoverBaseColor: "transparent",
    primaryTextColor: "#d7da1b",
    primaryHoverTextColor: "#3719db",
    secondaryTextColor: "#da1b73",
    secondaryHoverTextColor: "transparent",
    textFontColor: "#30da1b",
    hoverTextColor: "#d7da1b",
  },
  checkbox: {
    baseColor: "#00a1c9",
    checkColor: "#ffffff",
  },
  chip: {
    baseColor: "#1bc8da",
    accentColor: "",
    textColor: "#da1b73",
  },
  date: {
    baseColor: "#30da1b",
    accentColor: "#d7da1b",
  },
  dropdown: {
    baseColor: "#d7da1b",
    textColor: "#da1b73",
  },
  footer: {
    baseColor: "#da1b73",
    textColor: "#d7da1b",
    accentColor: "#c7562a",
  },
  header: {
    baseColor: "#d7da1b",
    accentColor: "#da1b73",
    textColor: "#ff7979",
    menuBaseColor: "#3719db",
    hamburguerColor: "#ff7979",
  },
  inputText: {
    selectedBaseColor: "#fb08ff",
  },
  paginator: {
    baseColor: "#1bc8da",
    accentColor: "#ffffff",
  },
  progressBar: {
    accentColor: "#0810ff",
    baseColor: "#da1b73",
  },
  radio: {
    baseColor: "#da1b73",
  },
  select: {
    baseColor: "#fb08ff",
  },
  sidenav: {
    baseColor: "#0810ff",
    arrowBaseColor: "#fb08ff",
    arrowAccentColor: "#da1b73",
  },
  slider: {
    baseColor: "#c7562a",
  },
  spinner: {
    accentColor: "#008ecc",
    baseColor: "#757575",
  },
  switch: {
    checkedBaseColor: "#30da1b",
  },
  table: {
    baseColor: "#30da1b",
    textColor: "#d7da1b",
  },
  tabs: {
    baseColor: "#30da1b",
  },
  toggle: {
    unselectedBaseColor: "#fb08ff",
    unselectedHoverBaseColor: "#1bc8da",
    unselectedTextColor: "#da1b73",
    unselectedHoverTextColor: "#ff7979",
    selectedBaseColor: "#30da1b",
    selectedHoverBaseColor: "#ba9cba",
    selectedTextColor: "#d7da1b",
    selectedHoverTextColor: "#1effea",
  },
  wizard: {
    baseColor: "#30da1b",
    textColor: "#d7da1b",
  },
  customs: {   
    '--fr-modal-bg': '#292929',
    '--localization-submenu-icon': '#a970e8',
    '--textarea-disabledFontColor': '#484848',
    '--select-disabledColor': '#484848',
    '--accordion-arrowColor': '#008ecc',
    '--accordion-focusOutline': '#008ecc',
    '--search-here': '#ffffff', 
    '--search-here-on-click': '#008ecc',  
    '--department_hierarchy': '#252526',
    '--button-secondaryHoverFontColor': '#ffffff',
    '--button-secondaryFontColor': '#ffffff',
    '--sub_head_color': '#008ecc61',
    '--grid_link_color': '#008ecc', 
    '--switch-uncheckedThumbBackgroundColor': '#ffffff',
    '--inputText-fontColor': '#ffffff',
    '--inputText-focusColor': '#008ecc',
    '--text-color': '#ffffff',
    '--button-disabledSecondaryOutlinedColor': '#008ecc',
    '--ag-balham-active-color': '#008ecc',
    '--ag-checkbox-unchecked-color': '#7f8c8d',
    '--ag-header-background-color': '#008ecc',
    '--ag-row-border-color': '#666666', 
    '--date-pickerFontColor': '#ffffff',
    '--date-selected-pickerFontColor': '#ffffff',
    '--date-pickerHoverDateBackgroundColor': '#cccccc', 
    '--date-pickerBackgroundColor': 'transparent', 
    '--date-color': '#ffffff',   
    '--calendar-body-cell-color': '#ffffff',
    '--date-pickerActualDate': '#008ecc',
    '--date-text-color': '#ffffff',
    '--alert-info-bg-color': '#3195a5',
    '--alert-info-text-color': '#213338',
    '--ag-header-foreground-color': '#ffffff',
    '-ag-secondary-foreground-color': '#ffffff',
    '--ag-background-color': '#333333',
    '--box-backgroundColor': '#3c3c3c',
    '--dialog-backgroundColor': '#424142', 
    '--dialog-car-backgroundColor': '#424142',   
    '--text-muted-color': '#ffffff',  
    '--select-panel-bg-color': '#3c3c3c', 
    '--select-color': '#cccccc',  
    '--chip-bg-color': 'transparent',
    '--chip-border-color': '#008ecc',
    '--chip-icon-color': '#008ecc',
    '--tab-underline-color': '#008ecc',
    '--text-hover-color': '#008ecc',
    '--transparent-color': 'transparent',    
    '--heading-text-color': '#c7bdbd',
    '--search-boder-color': '#b1b1b1',
    '--search-bg-color': '#1f1f1f',
    '--card-title-color': '#ffffff',
    '--card-subtitle-color': '#cec399',
    '--card-border-color': '#333333',
    '--card-bg-color': '#424242',
    '--landing-heading-color': '#008ecc',
    '--high-light-text-color': '#ffffff',
    '--logout-bg-color': '#3c3c3c',
    '--logout-text-color': '#ffffff',
    '--logout-brn-color': '#008ecc',
    '--logout-button-hover-color': '#ffffff',
    '--breadcrumb-border-color': '#008ecc',
    '--breadcrumb-bg-color': '#313131',
    '--breadcrumb-color': '#ffffff',
    '--breadcrumb-outline': '#424242',
    '--grid-icon-color': '#00a1c9',
    '--grid-nth-child-color': '#313131',
    '--grid-table-head-clr-hover': '#383737',
    '--grid-table-head-clr': '#424242',
    '--grid-head-clr': '#3a3838',
    '--grid-head-clr-grad': '#383737',
    '--grid-head-clr-grad-mix': '#403e3e',
    '--grid-head-text': '#000000',
    '--grid-text': '#ffffff',
    '--grid-line': '#424242',
    '--grid-bg': '#252423',
    '--tab-color': '#ffffff',
    '--section-heading-color': '#2b2b2b',
    '--leftMenuItem-border-color': '#403f3f',
    '--leftMenuItem-link-color': '#00a1c9',
    '--heading-color': '#D9D9D9',
    '--label-color': '#cccccc',
    '--slider-font-color': '#cccccc',
    '--checkmark-color': '#fff',
    '--placeholder-color': '#ffffff',
    '--mat-select-arrow-color': '#cccccc',
    '--mat-arrow-element-color': '#ffffff',
    '--mat-input-element-color': '#ffffff',
    '--mat-select-value-color': '#ffffff',
    '--mat-form-field-appearance-fill-color': '#ffffff',
    '--mat-form-field-appearance-standard-color': '#ffffff',
    '--mat-tab-header-color': '#424242',
    '--mat-background-icon-color': '#0067B3',
    '--mat-icon-color': '#00a1c9',
    '--border_color': '#666666',
    '--search_font_color': '#ffffff',
    '--icon_border_color': '#008ecc61',
    '--icon_color': '#000000',
    '--searchbackground': '#232223',
    '--source-icon': '#00a1c9',
    '--menupanel-arrowicon-color': '#444242',
    '--menupanel-center-background_color': '#292929',
    '--menupanel-left-background_color': '#252526',
    '--center_background_color': '#1f1f1f',
    '--background_color': '#333333',
    '--animate-background': '#66666666',
    '--header-background_color': '#3c3c3c',
    '--code-header-bg_color': '#3c3c3c',
    '--code-header-text_color': '#ffffff',
    '--menu_background_color': '#1f1f1f',
    '--group-heading': '#00a1c9',
    '--logo': 'url(./assets/images/dxclogo-white.png)',
    '--department-tree': 'url(./assets/images/32px-invert.png)',
    '--landing_textcolor': '#fff',
    '--button-secondaryOutlinedColor': '#008ecc',
    '--button-secondaryHoverBackgroundColor': 'transparent',
    '--button-secondaryActiveBackgroundColor': 'transparent',
    '--selected-icon-color': '#000000'
  }
};

export const lightTheme = {
  accordion: {
    accentColor: "#30da1b",
    textColor: "#666666",
  },
  button: {
    baseColor: "transparent",
    hoverBaseColor: "transparent",
    primaryTextColor: "#d7da1b",
    primaryHoverTextColor: "#3719db",
    secondaryTextColor: "#da1b73",
    secondaryHoverTextColor: "#da1b73",
    textFontColor: "#30da1b",
    hoverTextColor: "#d7da1b",
  },
  checkbox: {
    baseColor: "#00a1c9",
    checkColor: "#ffffff",
  },
  chip: {
    baseColor: "#1bc8da",
    accentColor: "",
    textColor: "#da1b73",
  },
  date: {
    baseColor: "#30da1b",
    accentColor: "#d7da1b",
  },
  dropdown: {
    baseColor: "#d7da1b",
    textColor: "#da1b73",
  },
  footer: {
    baseColor: "#da1b73",
    textColor: "#d7da1b",
    accentColor: "#c7562a",
  },
  header: {
    baseColor: "#d7da1b",
    accentColor: "#da1b73",
    textColor: "#ff7979",
    menuBaseColor: "#3719db",
    hamburguerColor: "#ff7979",
  },
  inputText: {
    selectedBaseColor: "#fb08ff",
  },
  paginator: {
    baseColor: "#1bc8da",
    accentColor: "#000000",
  },
  progressBar: {
    accentColor: "#0810ff",
    baseColor: "#da1b73",
  },
  radio: {
    baseColor: "#da1b73",
  },
  select: {
    baseColor: "#008ecc",
  },
  sidenav: {
    baseColor: "#0810ff",
    arrowBaseColor: "#fb08ff",
    arrowAccentColor: "#da1b73",
  },
  slider: {
    baseColor: "#c7562a",
  },
  spinner: {
    accentColor: "#008ecc",
    baseColor: "#ffffff",
  },
  switch: {
    checkedBaseColor: "#30da1b",
  },
  table: {
    baseColor: "#30da1b",
    textColor: "#d7da1b",
  },
  tabs: {
    baseColor: "#30da1b",
  },
  toggle: {
    unselectedBaseColor: "#fb08ff",
    unselectedHoverBaseColor: "#1bc8da",
    unselectedTextColor: "#da1b73",
    unselectedHoverTextColor: "#ff7979",
    selectedBaseColor: "#30da1b",
    selectedHoverBaseColor: "#ba9cba",
    selectedTextColor: "#d7da1b",
    selectedHoverTextColor: "#1effea",
  },
  wizard: {
    baseColor: "#30da1b",
    textColor: "#d7da1b",
  },
  customs: {  
    '--fr-modal-bg': '#ebebeb',
    '--localization-submenu-icon': '#a970e8',
    '--textarea-disabledFontColor': '#d9d9d9',
    '--select-disabledColor': '#d9d9d9',
    '--accordion-arrowColor': '#008ecc',
    '--accordion-focusOutline': '#008ecc',
    '--search-here': '#7f8c8d', 
    '--search-here-on-click': '#008ecc', 
    '--department_hierarchy': '#fafafa',
    '--button-secondaryHoverFontColor': '#000000',
    '--button-secondaryFontColor': '#ffffff',
    '--sub_head_color': '#008ecc61',
    '--grid_link_color': '#008ecc',
    '--switch-uncheckedThumbBackgroundColor': '#cccccc', 
    '--inputText-fontColor': '#000000',
    '--inputText-focusColor': '#008ecc',
    '--text-color': '#000000',
    '--button-disabledSecondaryOutlinedColor': '#008ecc',
    '--ag-balham-active-color': '#008ecc',
    '--ag-checkbox-unchecked-color': '#7f8c8d',
    '--ag-header-background-color': '#008ecc',
    '--ag-row-border-color': '#d9dcde',
    '--date-pickerFontColor': '#000000',
    '--date-selected-pickerFontColor': '#ffffff',
    '--date-pickerHoverDateBackgroundColor': '#cccccc',
    '--date-pickerBackgroundColor': 'transparent', 
    '--date-color': '#666666',   
    '--calendar-body-cell-color': '#666666',
    '--date-pickerActualDate': '#008ecc',
    '--date-text-color': '#ffffff',
    '--alert-info-bg-color': '#0c5460',
    '--alert-info-text-color': '#d1ecf1',
    '--ag-header-foreground-color': '#424242',
    '-ag-secondary-foreground-color': '#ffffff',
    '--ag-background-color': 'transparent',
    '--box-backgroundColor': '#ffffff',
    '--dialog-backgroundColor': '#ffffff',
    '--dialog-car-backgroundColor': 'transparent',
    '--text-muted-color': '#000000',
    '--select-panel-bg-color': '#ffffff',  
    '--select-color': '#000000',
    '--chip-bg-color': 'transparent',
    '--chip-border-color': '#008ecc',
    '--chip-icon-color': '#008ecc',
    '--froala-toolbar-svg-color': '#333333',
    '--froala-toolbar-bg-color': '#ffffff',
    '--froala-toolbar-border-color': '#cccccc',
    '--tab-underline-color': '#008ecc',
    '--heading-text-color': '#000000',
    '--search-boder-color': '#ddd5d5',
    '--search-bg-color': '#ffffff',
    '--card-title-color': '#000000',
    '--text-hover-color': '#008ecc',
    '--transparent-color': 'transparent',   
    '--card-subtitle-color': '#7f8c8d',
    '--card-border-color': '#ddd5d5',
    '--card-bg-color': '#ffffff',
    '--landing-heading-color': '#008ecc',
    '--high-light-text-color': '#424242',       
    '--logout-bg-color': '#ffffff',
    '--logout-text-color': '#000000',
    '--logout-brn-color': '#008ecc',
    '--logout-button-hover-color': '#000000',
    '--breadcrumb-border-color': '#008ecc',
    '--breadcrumb-bg-color': '#d9d9d9',
    '--breadcrumb-color': '#000000',
    '--breadcrumb-outline': '#D9D9D9',
    '--grid-icon-color': '#000000',
    '--grid-nth-child-color': '#f3f3f3',
    '--grid-table-head-clr-hover': '#d9d9d9',
    '--grid-table-head-clr': '#d9d9d9',
    '--grid-head-clr': '#f1f1f1',
    '--grid-head-clr-grad': '#f6f6f6',
    '--grid-head-clr-grad-mix': '#ffffff',
    '--grid-head-text': '#000000',
    '--grid-text': '#000000',
    '--grid-line': '#D9D9D9',
    '--grid-bg': '#ffffff',
    '--tab-color': '#000000',
    '--section-heading-color': '#D9D9D9',
    '--leftMenuItem-link-color': '#00a1c9',
    '--leftMenuItem-border-color': '#666666',
    '--heading-color': '#666666',
    '--label-color': '#666666',
    '--slider-font-color': '#666666',
    '--checkmark-color': '#fff',
    '--placeholder-color': '#d9d9d9',
    '--mat-select-arrow-color': '#000000',
    '--mat-arrow-element-color': '#000000',
    '--mat-input-element-color': '#000000',
    '--mat-select-value-color': '#000000',
    '--mat-form-field-appearance-fill-color': '#000000',
    '--mat-form-field-appearance-standard-color': '#000000',
    '--mat-tab-header-color': '#000000',
    '--mat-background-icon-color': '#0067B3',
    '--mat-icon-color': '#00a1c9',
    '--border_color': '#D9D9D9',
    '--search_font_color': '#666666',
    '--icon_border_color': '#008ecc61',
    '--icon_color': '#000000',
    '--searchbackground': '#d7d7d7',
    '--source-icon': '#00a1c9',
    '--menupanel-arrowicon-color': '#c7bdbd',
    '--menupanel-center-background_color': '#ffffff',
    '--menupanel-left-background_color': '#ffffff',
    '--background_color': '#ffffff',    
    '--animate-background': '#66666666',
    '--center_background_color': '#ffffff',
    '--header-background_color': '#ffffff',
    '--code-header-bg_color': '#d9d9d9',
    '--code-header-text_color': '#3a3a3a',
    '--menu_background_color': '#f3f1f1',
    '--group-heading': '#00a1c9',
    '--logo': 'url(./assets/images/dxclogo-black.png)',
    '--department-tree': 'url(./assets/images/32px.png)',
    '--landing_textcolor': '#000',
    '--button-secondaryOutlinedColor': '#008ecc',
    '--button-secondaryHoverBackgroundColor': 'transparent',
    '--button-secondaryActiveBackgroundColor': 'transparent',
    '--selected-icon-color': '#000000'
  }
};
