name: "Chromatic"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install lib dependencies
        run: cd projects/dxc-ngx-cdk && npm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          exitZeroOnChanges: true
          workingDir: projects/dxc-ngx-cdk
